"""add referenced_table to db_fields

Revision ID: 099b5e3b018e
Revises: 83c625925a9c
Create Date: 2025-07-16 20:50:21.986773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099b5e3b018e'
down_revision: Union[str, None] = '83c625925a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_fields', sa.Column('referenced_table', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_fields', 'referenced_table')
    # ### end Alembic commands ###
