"""create query-statistic-struct2 table

Revision ID: 1b11e7553749
Revises: 999c5206eebf
Create Date: 2025-07-01 11:04:44.983059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b11e7553749'
down_revision: Union[str, None] = '999c5206eebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_connection', sa.Column('status', sa.Boolean(), nullable=True))
    op.execute("UPDATE active_connection SET status = false") 
    op.alter_column('active_connection', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('active_connection_user_id_fkey'), 'active_connection', type_='foreignkey')
    op.drop_column('active_connection', 'user_id')
    op.add_column('db_statistics', sa.Column('table_count', sa.Integer(), nullable=False))
    op.add_column('db_statistics', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('db_statistics', sa.Column('procedure_count', sa.Integer(), nullable=False))
    op.add_column('db_statistics', sa.Column('function_count', sa.Integer(), nullable=False))
    op.add_column('db_statistics', sa.Column('trigger_count', sa.Integer(), nullable=False))
    op.add_column('db_statistics', sa.Column('index_count', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('db_statistics_db_connection_id_fkey'), 'db_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'db_statistics', 'db_connections', ['db_connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'db_statistics', type_='foreignkey')
    op.create_foreign_key(op.f('db_statistics_db_connection_id_fkey'), 'db_statistics', 'db_connections', ['db_connection_id'], ['id'])
    op.drop_column('db_statistics', 'index_count')
    op.drop_column('db_statistics', 'trigger_count')
    op.drop_column('db_statistics', 'function_count')
    op.drop_column('db_statistics', 'procedure_count')
    op.drop_column('db_statistics', 'view_count')
    op.drop_column('db_statistics', 'table_count')
    op.add_column('active_connection', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('active_connection_user_id_fkey'), 'active_connection', 'users', ['user_id'], ['id'])
    op.alter_column('active_connection', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('active_connection', 'status')
    # ### end Alembic commands ###
