"""Fix FK in TableRowCountCache4

Revision ID: 1e18061cb84a
Revises: 8f75f7a38abb
Create Date: 2025-07-13 00:40:39.418405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e18061cb84a'
down_revision: Union[str, None] = '8f75f7a38abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_statistics', sa.Column('server_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_statistics', 'server_version')
    # ### end Alembic commands ###
