"""db_enum

Revision ID: 3a8b54326e2a
Revises: 7f07f16f42ac
Create Date: 2025-07-02 16:14:54.065386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8b54326e2a'
down_revision: Union[str, None] = '7f07f16f42ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_fields', sa.Column('is_unique', sa.Boolean(), nullable=True))
    op.add_column('db_fields', sa.Column('is_auto_increment', sa.Boolean(), nullable=True))
    op.add_column('db_fields', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('db_fields', sa.Column('precision', sa.Integer(), nullable=True))
    op.add_column('db_fields', sa.Column('scale', sa.Integer(), nullable=True))
    op.add_column('db_structures', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('db_structures', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_structure_connection_table', 'db_structures', ['db_connection_id', 'table_name', 'schema_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_structure_connection_table', 'db_structures', type_='unique')
    op.drop_column('db_structures', 'is_deleted')
    op.drop_column('db_structures', 'updated_at')
    op.drop_column('db_fields', 'scale')
    op.drop_column('db_fields', 'precision')
    op.drop_column('db_fields', 'length')
    op.drop_column('db_fields', 'is_auto_increment')
    op.drop_column('db_fields', 'is_unique')
    # ### end Alembic commands ###
