"""initial migration 5

Revision ID: 4087488abe74
Revises: cc4e97d56a8e
Create Date: 2026-01-14 10:20:43.167470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4087488abe74'
down_revision: Union[str, None] = 'cc4e97d56a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settings', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'sidebar_collapsed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.drop_constraint(op.f('settings_user_id_fkey'), 'settings', type_='foreignkey')
    op.create_foreign_key(None, 'settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_settings_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'settings_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_settings_id_fkey'), 'users', 'settings', ['settings_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.create_foreign_key(op.f('settings_user_id_fkey'), 'settings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.alter_column('settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('settings', 'sidebar_collapsed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('settings', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
