"""adicionei coluna de estado do objecto

Revision ID: 48a01c219409
Revises: 4f8ea9b70aec
Create Date: 2026-02-22 20:04:47.923117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a01c219409'
down_revision: Union[str, None] = '4f8ea9b70aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('db_enum_fields', sa.Column('status', sa.String(20), nullable=False, server_default='active'))
    op.add_column('cargos', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    op.add_column('db_fields', sa.Column('status', sa.String(20), nullable=False, server_default='active'))
    op.add_column('db_structures', sa.Column('status', sa.String(20), nullable=False, server_default='active'))
    op.add_column('empresas', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_IP', sa.String(length=45), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_enum_fields', 'status')
    
    # 2. Depois deletamos o objeto ENUM do banco
    status_enum = sa.Enum('active', 'deleted', 'error', 'inactive', name='estrutura_status_enum')
    status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('roles', 'is_active')
    op.drop_column('refresh_tokens', 'is_active')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'user_IP')
    op.drop_column('empresas', 'is_active')
    op.drop_column('db_structures', 'status')
    op.drop_column('db_fields', 'status')
    op.drop_column('db_enum_fields', 'status')
    op.drop_column('cargos', 'is_active')
    # ### end Alembic commands ###
