"""adicionei coluna de estado do objecto 3

Revision ID: 50a62ca2d780
Revises: 8b25a4fff415
Create Date: 2026-02-28 08:23:12.624188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a62ca2d780'
down_revision: Union[str, None] = '8b25a4fff415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('email_notifications', sa.Boolean(), nullable=False))
    op.add_column('settings', sa.Column('app_notifications', sa.Boolean(), nullable=False))
    op.add_column('settings', sa.Column('timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'timezone')
    op.drop_column('settings', 'app_notifications')
    op.drop_column('settings', 'email_notifications')
    # ### end Alembic commands ###
