"""add campo em db_field

Revision ID: 53dc8de4bf7d
Revises: d964ec09a2db
Create Date: 2026-04-05 11:53:25.508278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dc8de4bf7d'
down_revision: Union[str, None] = 'd964ec09a2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_column')
    op.add_column('db_fields', sa.Column('is_unsigned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_fields', 'is_unsigned')
    op.create_table('test_column',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_first_column', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.UniqueConstraint('test_first_column', name=op.f('test_column_test_first_column_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='kjsbdekjesbefk'
    )
    # ### end Alembic commands ###
