"""Adiciona chave primária composta em db_enum_fields

Revision ID: 6aeae21bc4fa
Revises: 4b52608a6089
Create Date: 2025-07-03 09:56:51.003083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aeae21bc4fa'
down_revision: Union[str, None] = '4b52608a6089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_enum_fields',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['db_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id', 'valor')
    )
    op.create_index('ix_enum_field_field_id', 'db_enum_fields', ['field_id'], unique=False)
    op.drop_table('db_enum_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_enum_field',
    sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['db_fields.id'], name=op.f('db_enum_field_field_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id', 'valor', name=op.f('db_enum_field_pkey'))
    )
    op.drop_index('ix_enum_field_field_id', table_name='db_enum_fields')
    op.drop_table('db_enum_fields')
    # ### end Alembic commands ###
