"""add user_auth_providers 2

Revision ID: 75f07d6c2e7f
Revises: 102a3276d88f
Create Date: 2026-04-22 21:56:13.131252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f07d6c2e7f'
down_revision: Union[str, None] = '102a3276d88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_providers', sa.Column('location', sa.String(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('provider_username', sa.String(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('profile_url', sa.Text(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('user_auth_providers', sa.Column('provider_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_providers', 'provider_payload')
    op.drop_column('user_auth_providers', 'last_synced_at')
    op.drop_column('user_auth_providers', 'token_expires_at')
    op.drop_column('user_auth_providers', 'refresh_token')
    op.drop_column('user_auth_providers', 'access_token')
    op.drop_column('user_auth_providers', 'profile_url')
    op.drop_column('user_auth_providers', 'provider_username')
    op.drop_column('user_auth_providers', 'bio')
    op.drop_column('user_auth_providers', 'location')
    # ### end Alembic commands ###
