"""corrigindo relacionamento project-typeprojecto 3s

Revision ID: 7684b454454e
Revises: b8d0b09f5750
Create Date: 2025-10-19 14:19:35.549000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7684b454454e'
down_revision: Union[str, None] = 'b8d0b09f5750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('comentario_is_validated', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'comentario_is_validated')
    # ### end Alembic commands ###
