"""add campo field_reference

Revision ID: 7ba0c52174a3
Revises: 099b5e3b018e
Create Date: 2025-08-24 08:37:05.015216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba0c52174a3'
down_revision: Union[str, None] = '099b5e3b018e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_fields', sa.Column('field_references', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_fields', 'field_references')
    # ### end Alembic commands ###
