"""create db_structures and db_enum

Revision ID: 7f07f16f42ac
Revises: e476cca0e07c
Create Date: 2025-07-02 15:05:41.449193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f07f16f42ac'
down_revision: Union[str, None] = 'e476cca0e07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_enum_field',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['db_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('field_id', 'valor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_enum_field')
    # ### end Alembic commands ###
