"""corrigindo relacionamento project-typeprojecto 2

Revision ID: 81b02f2f8288
Revises: aed95d4a8dfb
Create Date: 2025-10-16 12:02:33.828449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b02f2f8288'
down_revision: Union[str, None] = 'aed95d4a8dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
