"""Fix field

Revision ID: 83c625925a9c
Revises: 1e18061cb84a
Create Date: 2025-07-15 16:11:33.924520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c625925a9c'
down_revision: Union[str, None] = '1e18061cb84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_fields', sa.Column('is_ForeignKey', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_fields', 'is_ForeignKey')
    # ### end Alembic commands ###
