"""statistic table

Revision ID: 88c31600dcc8
Revises: 1b11e7553749
Create Date: 2025-07-01 11:17:20.833879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c31600dcc8'
down_revision: Union[str, None] = '1b11e7553749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_connection', sa.Column('status', sa.Boolean(), nullable=True))
 
    op.execute("UPDATE active_connection SET status = false") 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_connection', 'status')
    # ### end Alembic commands ###
