"""adicionei coluna de estado do objecto 2

Revision ID: 8b25a4fff415
Revises: 48a01c219409
Create Date: 2026-02-23 16:18:58.501787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b25a4fff415'
down_revision: Union[str, None] = '48a01c219409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_structures', sa.Column('Engine', sa.String(length=50), nullable=True))
    op.add_column('db_structures', sa.Column('Charset', sa.String(length=50), nullable=True))
    op.add_column('db_structures', sa.Column('Collation', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_structures', 'Collation')
    op.drop_column('db_structures', 'Charset')
    op.drop_column('db_structures', 'Engine')
    # ### end Alembic commands ###
