"""descrição da mudança

Revision ID: 96042e04fc83
Revises: 1a94b0f9d712
Create Date: 2025-06-22 18:47:37.753257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96042e04fc83'
down_revision: Union[str, None] = '1a94b0f9d712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connections', sa.Column('trustServerCertificate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_connections', 'trustServerCertificate')
    # ### end Alembic commands ###
