"""nova Melhorias no modelo DBEnum_field

Revision ID: 967205ed0bfc
Revises: 6aeae21bc4fa
Create Date: 2025-07-03 15:33:42.505535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967205ed0bfc'
down_revision: Union[str, None] = '6aeae21bc4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
