"""create query-statistic-struct table

Revision ID: 999c5206eebf
Revises: 96042e04fc83
Create Date: 2025-06-29 17:50:38.158118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '999c5206eebf'
down_revision: Union[str, None] = '96042e04fc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_statistics', sa.Column('last_query_at', sa.DateTime(), nullable=True))
    op.alter_column('db_statistics', 'db_connection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('db_statistics', 'tables_connected',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('db_statistics', 'queries_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('db_statistics', 'records_analyzed',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('db_statistics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_db_statistics_db_connection_id'), 'db_statistics', ['db_connection_id'], unique=False)
    op.add_column('query_history', sa.Column('query_type', sa.String(), nullable=True))
    op.add_column('query_history', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('query_history', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('query_history', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('query_history', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('query_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_history', 'db_connection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_history', 'query',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('query_history', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('settings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'updated_at')
    op.alter_column('query_history', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('query_history', 'query',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('query_history', 'db_connection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('query_history', 'updated_at')
    op.drop_column('query_history', 'tags')
    op.drop_column('query_history', 'is_favorite')
    op.drop_column('query_history', 'error_message')
    op.drop_column('query_history', 'query_type')
    op.drop_index(op.f('ix_db_statistics_db_connection_id'), table_name='db_statistics')
    op.alter_column('db_statistics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('db_statistics', 'records_analyzed',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('db_statistics', 'queries_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('db_statistics', 'tables_connected',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('db_statistics', 'db_connection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('db_statistics', 'last_query_at')
    # ### end Alembic commands ###
