"""fild status

Revision ID: acee99d851c1
Revises: 1134637b9e0c
Create Date: 2025-07-01 11:34:17.484456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acee99d851c1'
down_revision: Union[str, None] = '1134637b9e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_connection', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_connection', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
