"""corrigindo relacionamento project-typeprojecto

Revision ID: aed95d4a8dfb
Revises: 
Create Date: 2025-10-16 11:43:39.696822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed95d4a8dfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('typeprojecto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('projects', sa.Column('type_project_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'projects', 'typeprojecto', ['type_project_id'], ['id'], ondelete='SET NULL')
    op.add_column('sprints', sa.Column('cancelled', sa.Boolean(), nullable=True))
    op.add_column('sprints', sa.Column('motivo_cancelamento', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('role_id', sa.String(), nullable=True))
    op.alter_column('usuarios', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'usuarios', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.alter_column('usuarios', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usuarios', 'role_id')
    op.drop_column('tasks', 'cancelled_at')
    op.drop_column('tasks', 'cancel_reason')
    op.drop_column('tasks', 'is_active')
    op.drop_column('sprints', 'motivo_cancelamento')
    op.drop_column('sprints', 'cancelled')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'cancelled_at')
    op.drop_column('projects', 'cancel_reason')
    op.drop_column('projects', 'is_active')
    op.drop_column('projects', 'type_project_id')
    op.drop_table('typeprojecto')
    op.drop_table('roles')
    # ### end Alembic commands ###
