"""corrigindo relacionamento project-typeprojecto 2s

Revision ID: b8d0b09f5750
Revises: 81b02f2f8288
Create Date: 2025-10-16 13:01:38.271272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d0b09f5750'
down_revision: Union[str, None] = '81b02f2f8288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_cargos_id'), 'cargos', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tamanho', sa.String(length=50), nullable=True),
    sa.Column('nif', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.add_column('users', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cargo_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'cargos', ['cargo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'nome_empresa')
    op.drop_column('users', 'cargo')
    op.drop_column('users', 'tamanho_empresa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tamanho_empresa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('cargo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nome_empresa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'criado_em')
    op.drop_column('users', 'cargo_id')
    op.drop_column('users', 'empresa_id')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_cargos_id'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
