"""initial migration 4

Revision ID: cc4e97d56a8e
Revises: 3a852bf23783
Create Date: 2026-01-14 10:01:30.932217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4e97d56a8e'
down_revision: Union[str, None] = '3a852bf23783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'settings', ['settings_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'settings_id')
    # ### end Alembic commands ###
