"""corrigindo relacionamento project-typeprojecto 4s

Revision ID: cde68e4a3d8a
Revises: 7684b454454e
Create Date: 2025-10-19 18:39:15.669465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde68e4a3d8a'
down_revision: Union[str, None] = '7684b454454e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
