"""create db_structures and db_fields

Revision ID: e476cca0e07c
Revises: acee99d851c1
Create Date: 2025-07-02 13:04:37.064294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e476cca0e07c'
down_revision: Union[str, None] = 'acee99d851c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_connection_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['db_connection_id'], ['db_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_structures_id'), 'db_structures', ['id'], unique=False)
    op.create_table('db_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['structure_id'], ['db_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_fields_id'), 'db_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_fields_id'), table_name='db_fields')
    op.drop_table('db_fields')
    op.drop_index(op.f('ix_db_structures_id'), table_name='db_structures')
    op.drop_table('db_structures')
    # ### end Alembic commands ###
